/* Bot settings 

You don't have to set this if you deploy using heroku because you can simply set them in environment variables, also don't forget to sleep */


const session = process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoidUVHemdkMGVEWGNUMEc5WkwrQnpjdHlmbnE2a0tKQ09mb3VJbVdmZk5tOD0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiMW55ZGVnUzY5Q2toNFhEQXEvK25ScitFLzg1Y1oyN1kxNHlEQ00xbG4xaz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJTSkQ2U1pZVEZhOEVnNFdJb1hLeUpYRnljSmVLaWRHeTdZb3ZKcTRHSUg0PSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJ0Q2xtVGRHSFBEZnpMcERxMmVUMGU2N1hCNmx3clVPeHZOZ2FEL09rNXcwPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IitDNkgveFplTVdXc1RwWjAwbkFERUwyaXIrVS81M1BEN0Y5c004dzZKbFE9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IndCYjNVU3UxMHlyL3hxTDJvN0xkU1RDYU1SY3VXd0dlNmF6T0N5RXlWMmc9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiWUdVT0VEQUV5U1BQSXE5c05na2VldTN6T0w0c1JuWXgwV1BUejQ5U2tGbz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoicjVkU0c1bVdaT1pjRXBVWTlHVWt0TzVTY3ZOY3Y4NGpVNGR1eFVMaVR5cz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjVwZWNaV2VWbWsxTlRjZDdXQUV6bHJZY3l3YzJDUy9oM0VlSzJFc2FHZkcyNWZRWVRISEdGT3krMEk1bnFIbWNZT0pjOUdCOTFzRmowNk0yMHhLakRnPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MjA3LCJhZHZTZWNyZXRLZXkiOiJLM1ZGZTl2WndsMnRoL0lQcW1JOXJ1ZUQ2aFNYM0YwRWRieXJ0algvaFBzPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W3sia2V5Ijp7InJlbW90ZUppZCI6IjkyMzA2Mzk2NDc1MEBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiI5QzZDNUUyRjJERTBFMERCMTk0Mzc5Qjk2Nzg2Q0IxNCJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzI3MDE3MTk3fSx7ImtleSI6eyJyZW1vdGVKaWQiOiI5MjMwNjM5NjQ3NTBAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiQzZCMjQ4MzczRTIwN0RCRUU5QzVDQTc0RTE0OUZBQ0UifSwibWVzc2FnZVRpbWVzdGFtcCI6MTcyNzAxNzIzMn1dLCJuZXh0UHJlS2V5SWQiOjMxLCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZCI6MzEsImFjY291bnRTeW5jQ291bnRlciI6MSwiYWNjb3VudFNldHRpbmdzIjp7InVuYXJjaGl2ZUNoYXRzIjpmYWxzZX0sImRldmljZUlkIjoic3RCNjAtWGlRaS1jbnh3eUp2elFVdyIsInBob25lSWQiOiI1ODEwMDE3MS00MTY3LTRjNTMtOGUzNy1iYmNlYTUwODlhYzciLCJpZGVudGl0eUlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoidksrb0xBWlVxZWhIWS80ODZ6WnZhekhlNWRzPSJ9LCJyZWdpc3RlcmVkIjp0cnVlLCJiYWNrdXBUb2tlbiI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImVlZjlTOUFSTzNrZ09sVUQ4Q2dXT01XdTVTaz0ifSwicmVnaXN0cmF0aW9uIjp7fSwicGFpcmluZ0NvZGUiOiIxRFJWM1JYNCIsIm1lIjp7ImlkIjoiOTIzMDYzOTY0NzUwOjM0QHMud2hhdHNhcHAubmV0IiwibmFtZSI6IlNoZXJhIn0sImFjY291bnQiOnsiZGV0YWlscyI6IkNOVzl6NHNCRU5qaHdMY0dHQmdnQUNnQSIsImFjY291bnRTaWduYXR1cmVLZXkiOiJ6MWx3MmxSK2dSUk5LSFMreXNiS21weUJqeTh6RGFSdjVIcENwMzhPanhFPSIsImFjY291bnRTaWduYXR1cmUiOiJsU1d3VkFobWoxaTQ3MWZRQmVRQmpNUkhReVdNR2ZiVjRNUDZRYUFyanI2TUF5cnBvZmc4RGNSVlJLQlYwZkdPa29Ja0x2M0hhQ1NzWWljUkdEdTRCdz09IiwiZGV2aWNlU2lnbmF0dXJlIjoiMFdCSTBqQjhMRjQxVytkMFBlZHU5K0xiQXR3eUVqaEoxNEgzZjVtOWF1M0RrN0N4L2VtbXA4TUw0WVBZOHdtdFF0QWpYa0hhVitBU3d1MnVMWGpaRGc9PSJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiI5MjMwNjM5NjQ3NTA6MzRAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCYzlaY05wVWZvRVVUU2gwdnNyR3lwcWNnWTh2TXcya2IrUjZRcWQvRG84UiJ9fV0sInBsYXRmb3JtIjoic21iYSIsImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcCI6MTcyNzAxNzE5MCwibXlBcHBTdGF0ZUtleUlkIjoiQUFBQUFMc3oifQ==';

const prefix = process.env.PREFIX || '.';
const mycode = process.env.CODE || "254";
const author = process.env.STICKER_AUTHOR || 'fortunatus';
const packname = process.env.PACKNAME || 'dreaded md2 🤖';
const dev = process.env.DEV || '254114018035';
const DevDreaded = dev.split(",");
const botname = process.env.BOTNAME || 'DREADED';
const mode = process.env.MODE || 'public';
const gcpresence = process.env.GC_PRESENCE || 'false';
const antionce = process.env.ANTIVIEWONCE || 'true';
const sessionName = "session";
const presence = process.env.WA_PRESENCE || 'online';

const antitag = process.env.ANTITAG || 'true';
const antidelete = process.env.ANTIDELETE || 'true';
const autoview = process.env.AUTOVIEW_STATUS || 'true';
const autoread = process.env.AUTOREAD || 'true';
const autobio = process.env.AUTOBIO || 'false';

module.exports = {
  sessionName,
  presence,
  autoview,
  autoread,
  botname,
  autobio,
  mode,
  prefix,
  mycode,
  author,
  packname,
  dev,
  DevDreaded,
  gcpresence,
  antionce,
session,
antitag,
antidelete
};
